server:
  port: 8080
  max-http-header-size: 102400
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      repositories:
        enabled: false
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
      username: root
      password: root
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/**/*Mapper.xml
  type-aliases-package: classpath*:com/shixinlei/demo/**/domain
  global-config:
    db-config:
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
